// Generated by gencpp from file multipoint_navigation_receiver/set_goal_srv.msg
// DO NOT EDIT!


#ifndef MULTIPOINT_NAVIGATION_RECEIVER_MESSAGE_SET_GOAL_SRV_H
#define MULTIPOINT_NAVIGATION_RECEIVER_MESSAGE_SET_GOAL_SRV_H

#include <ros/service_traits.h>


#include <multipoint_navigation_receiver/set_goal_srvRequest.h>
#include <multipoint_navigation_receiver/set_goal_srvResponse.h>


namespace multipoint_navigation_receiver
{

struct set_goal_srv
{

typedef set_goal_srvRequest Request;
typedef set_goal_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_goal_srv
} // namespace multipoint_navigation_receiver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multipoint_navigation_receiver::set_goal_srv > {
  static const char* value()
  {
    return "343d08ce7c6d1af4bde14bcd847ac4f3";
  }

  static const char* value(const ::multipoint_navigation_receiver::set_goal_srv&) { return value(); }
};

template<>
struct DataType< ::multipoint_navigation_receiver::set_goal_srv > {
  static const char* value()
  {
    return "multipoint_navigation_receiver/set_goal_srv";
  }

  static const char* value(const ::multipoint_navigation_receiver::set_goal_srv&) { return value(); }
};


// service_traits::MD5Sum< ::multipoint_navigation_receiver::set_goal_srvRequest> should match
// service_traits::MD5Sum< ::multipoint_navigation_receiver::set_goal_srv >
template<>
struct MD5Sum< ::multipoint_navigation_receiver::set_goal_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multipoint_navigation_receiver::set_goal_srv >::value();
  }
  static const char* value(const ::multipoint_navigation_receiver::set_goal_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multipoint_navigation_receiver::set_goal_srvRequest> should match
// service_traits::DataType< ::multipoint_navigation_receiver::set_goal_srv >
template<>
struct DataType< ::multipoint_navigation_receiver::set_goal_srvRequest>
{
  static const char* value()
  {
    return DataType< ::multipoint_navigation_receiver::set_goal_srv >::value();
  }
  static const char* value(const ::multipoint_navigation_receiver::set_goal_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multipoint_navigation_receiver::set_goal_srvResponse> should match
// service_traits::MD5Sum< ::multipoint_navigation_receiver::set_goal_srv >
template<>
struct MD5Sum< ::multipoint_navigation_receiver::set_goal_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multipoint_navigation_receiver::set_goal_srv >::value();
  }
  static const char* value(const ::multipoint_navigation_receiver::set_goal_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multipoint_navigation_receiver::set_goal_srvResponse> should match
// service_traits::DataType< ::multipoint_navigation_receiver::set_goal_srv >
template<>
struct DataType< ::multipoint_navigation_receiver::set_goal_srvResponse>
{
  static const char* value()
  {
    return DataType< ::multipoint_navigation_receiver::set_goal_srv >::value();
  }
  static const char* value(const ::multipoint_navigation_receiver::set_goal_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTIPOINT_NAVIGATION_RECEIVER_MESSAGE_SET_GOAL_SRV_H
