// Generated by gencpp from file multipoint_navigation_receiver/set_goal_srvRequest.msg
// DO NOT EDIT!


#ifndef MULTIPOINT_NAVIGATION_RECEIVER_MESSAGE_SET_GOAL_SRVREQUEST_H
#define MULTIPOINT_NAVIGATION_RECEIVER_MESSAGE_SET_GOAL_SRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Quaternion.h>

namespace multipoint_navigation_receiver
{
template <class ContainerAllocator>
struct set_goal_srvRequest_
{
  typedef set_goal_srvRequest_<ContainerAllocator> Type;

  set_goal_srvRequest_()
    : positions()
    , quaternions()  {
    }
  set_goal_srvRequest_(const ContainerAllocator& _alloc)
    : positions(_alloc)
    , quaternions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _positions_type;
  _positions_type positions;

   typedef std::vector< ::geometry_msgs::Quaternion_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Quaternion_<ContainerAllocator> >> _quaternions_type;
  _quaternions_type quaternions;





  typedef boost::shared_ptr< ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_goal_srvRequest_

typedef ::multipoint_navigation_receiver::set_goal_srvRequest_<std::allocator<void> > set_goal_srvRequest;

typedef boost::shared_ptr< ::multipoint_navigation_receiver::set_goal_srvRequest > set_goal_srvRequestPtr;
typedef boost::shared_ptr< ::multipoint_navigation_receiver::set_goal_srvRequest const> set_goal_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator1> & lhs, const ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.positions == rhs.positions &&
    lhs.quaternions == rhs.quaternions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator1> & lhs, const ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multipoint_navigation_receiver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3e802c88b376c0e80360d0e2f07318c";
  }

  static const char* value(const ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3e802c88b376c0eULL;
  static const uint64_t static_value2 = 0x80360d0e2f07318cULL;
};

template<class ContainerAllocator>
struct DataType< ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multipoint_navigation_receiver/set_goal_srvRequest";
  }

  static const char* value(const ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3[] positions\n"
"geometry_msgs/Quaternion[] quaternions\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.positions);
      stream.next(m.quaternions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_goal_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multipoint_navigation_receiver::set_goal_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.positions[i]);
    }
    s << indent << "quaternions[]" << std::endl;
    for (size_t i = 0; i < v.quaternions.size(); ++i)
    {
      s << indent << "  quaternions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "    ", v.quaternions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTIPOINT_NAVIGATION_RECEIVER_MESSAGE_SET_GOAL_SRVREQUEST_H
