// Generated by gencpp from file waypoints/Delete_Wp.msg
// DO NOT EDIT!


#ifndef WAYPOINTS_MESSAGE_DELETE_WP_H
#define WAYPOINTS_MESSAGE_DELETE_WP_H

#include <ros/service_traits.h>


#include <waypoints/Delete_WpRequest.h>
#include <waypoints/Delete_WpResponse.h>


namespace waypoints
{

struct Delete_Wp
{

typedef Delete_WpRequest Request;
typedef Delete_WpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Delete_Wp
} // namespace waypoints


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::waypoints::Delete_Wp > {
  static const char* value()
  {
    return "586d8f413500dd2c0010cf7506a3071c";
  }

  static const char* value(const ::waypoints::Delete_Wp&) { return value(); }
};

template<>
struct DataType< ::waypoints::Delete_Wp > {
  static const char* value()
  {
    return "waypoints/Delete_Wp";
  }

  static const char* value(const ::waypoints::Delete_Wp&) { return value(); }
};


// service_traits::MD5Sum< ::waypoints::Delete_WpRequest> should match
// service_traits::MD5Sum< ::waypoints::Delete_Wp >
template<>
struct MD5Sum< ::waypoints::Delete_WpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::waypoints::Delete_Wp >::value();
  }
  static const char* value(const ::waypoints::Delete_WpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoints::Delete_WpRequest> should match
// service_traits::DataType< ::waypoints::Delete_Wp >
template<>
struct DataType< ::waypoints::Delete_WpRequest>
{
  static const char* value()
  {
    return DataType< ::waypoints::Delete_Wp >::value();
  }
  static const char* value(const ::waypoints::Delete_WpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::waypoints::Delete_WpResponse> should match
// service_traits::MD5Sum< ::waypoints::Delete_Wp >
template<>
struct MD5Sum< ::waypoints::Delete_WpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::waypoints::Delete_Wp >::value();
  }
  static const char* value(const ::waypoints::Delete_WpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoints::Delete_WpResponse> should match
// service_traits::DataType< ::waypoints::Delete_Wp >
template<>
struct DataType< ::waypoints::Delete_WpResponse>
{
  static const char* value()
  {
    return DataType< ::waypoints::Delete_Wp >::value();
  }
  static const char* value(const ::waypoints::Delete_WpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAYPOINTS_MESSAGE_DELETE_WP_H
