// Generated by gencpp from file waypoints/Groups_Wp.msg
// DO NOT EDIT!


#ifndef WAYPOINTS_MESSAGE_GROUPS_WP_H
#define WAYPOINTS_MESSAGE_GROUPS_WP_H

#include <ros/service_traits.h>


#include <waypoints/Groups_WpRequest.h>
#include <waypoints/Groups_WpResponse.h>


namespace waypoints
{

struct Groups_Wp
{

typedef Groups_WpRequest Request;
typedef Groups_WpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Groups_Wp
} // namespace waypoints


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::waypoints::Groups_Wp > {
  static const char* value()
  {
    return "15bacb1518f81a33d47562f4809b35a3";
  }

  static const char* value(const ::waypoints::Groups_Wp&) { return value(); }
};

template<>
struct DataType< ::waypoints::Groups_Wp > {
  static const char* value()
  {
    return "waypoints/Groups_Wp";
  }

  static const char* value(const ::waypoints::Groups_Wp&) { return value(); }
};


// service_traits::MD5Sum< ::waypoints::Groups_WpRequest> should match
// service_traits::MD5Sum< ::waypoints::Groups_Wp >
template<>
struct MD5Sum< ::waypoints::Groups_WpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::waypoints::Groups_Wp >::value();
  }
  static const char* value(const ::waypoints::Groups_WpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoints::Groups_WpRequest> should match
// service_traits::DataType< ::waypoints::Groups_Wp >
template<>
struct DataType< ::waypoints::Groups_WpRequest>
{
  static const char* value()
  {
    return DataType< ::waypoints::Groups_Wp >::value();
  }
  static const char* value(const ::waypoints::Groups_WpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::waypoints::Groups_WpResponse> should match
// service_traits::MD5Sum< ::waypoints::Groups_Wp >
template<>
struct MD5Sum< ::waypoints::Groups_WpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::waypoints::Groups_Wp >::value();
  }
  static const char* value(const ::waypoints::Groups_WpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoints::Groups_WpResponse> should match
// service_traits::DataType< ::waypoints::Groups_Wp >
template<>
struct DataType< ::waypoints::Groups_WpResponse>
{
  static const char* value()
  {
    return DataType< ::waypoints::Groups_Wp >::value();
  }
  static const char* value(const ::waypoints::Groups_WpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAYPOINTS_MESSAGE_GROUPS_WP_H
