// Generated by gencpp from file waypoints/Groups_WpRequest.msg
// DO NOT EDIT!


#ifndef WAYPOINTS_MESSAGE_GROUPS_WPREQUEST_H
#define WAYPOINTS_MESSAGE_GROUPS_WPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace waypoints
{
template <class ContainerAllocator>
struct Groups_WpRequest_
{
  typedef Groups_WpRequest_<ContainerAllocator> Type;

  Groups_WpRequest_()
    : option()
    , group_name()  {
    }
  Groups_WpRequest_(const ContainerAllocator& _alloc)
    : option(_alloc)
    , group_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _option_type;
  _option_type option;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _group_name_type;
  _group_name_type group_name;





  typedef boost::shared_ptr< ::waypoints::Groups_WpRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::waypoints::Groups_WpRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Groups_WpRequest_

typedef ::waypoints::Groups_WpRequest_<std::allocator<void> > Groups_WpRequest;

typedef boost::shared_ptr< ::waypoints::Groups_WpRequest > Groups_WpRequestPtr;
typedef boost::shared_ptr< ::waypoints::Groups_WpRequest const> Groups_WpRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::waypoints::Groups_WpRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::waypoints::Groups_WpRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::waypoints::Groups_WpRequest_<ContainerAllocator1> & lhs, const ::waypoints::Groups_WpRequest_<ContainerAllocator2> & rhs)
{
  return lhs.option == rhs.option &&
    lhs.group_name == rhs.group_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::waypoints::Groups_WpRequest_<ContainerAllocator1> & lhs, const ::waypoints::Groups_WpRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace waypoints

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::waypoints::Groups_WpRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoints::Groups_WpRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waypoints::Groups_WpRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waypoints::Groups_WpRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoints::Groups_WpRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoints::Groups_WpRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::waypoints::Groups_WpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f302dec009f435cabadb389876ca3e8";
  }

  static const char* value(const ::waypoints::Groups_WpRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f302dec009f435cULL;
  static const uint64_t static_value2 = 0xabadb389876ca3e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::waypoints::Groups_WpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "waypoints/Groups_WpRequest";
  }

  static const char* value(const ::waypoints::Groups_WpRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::waypoints::Groups_WpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string  option               \n"
"string  group_name               \n"
;
  }

  static const char* value(const ::waypoints::Groups_WpRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::waypoints::Groups_WpRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.option);
      stream.next(m.group_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Groups_WpRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::waypoints::Groups_WpRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::waypoints::Groups_WpRequest_<ContainerAllocator>& v)
  {
    s << indent << "option: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.option);
    s << indent << "group_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.group_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAYPOINTS_MESSAGE_GROUPS_WPREQUEST_H
