// Generated by gencpp from file waypoints/Load_WpResponse.msg
// DO NOT EDIT!


#ifndef WAYPOINTS_MESSAGE_LOAD_WPRESPONSE_H
#define WAYPOINTS_MESSAGE_LOAD_WPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace waypoints
{
template <class ContainerAllocator>
struct Load_WpResponse_
{
  typedef Load_WpResponse_<ContainerAllocator> Type;

  Load_WpResponse_()
    : success(false)  {
    }
  Load_WpResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::waypoints::Load_WpResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::waypoints::Load_WpResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Load_WpResponse_

typedef ::waypoints::Load_WpResponse_<std::allocator<void> > Load_WpResponse;

typedef boost::shared_ptr< ::waypoints::Load_WpResponse > Load_WpResponsePtr;
typedef boost::shared_ptr< ::waypoints::Load_WpResponse const> Load_WpResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::waypoints::Load_WpResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::waypoints::Load_WpResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::waypoints::Load_WpResponse_<ContainerAllocator1> & lhs, const ::waypoints::Load_WpResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::waypoints::Load_WpResponse_<ContainerAllocator1> & lhs, const ::waypoints::Load_WpResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace waypoints

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::waypoints::Load_WpResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoints::Load_WpResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waypoints::Load_WpResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waypoints::Load_WpResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoints::Load_WpResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoints::Load_WpResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::waypoints::Load_WpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::waypoints::Load_WpResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::waypoints::Load_WpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "waypoints/Load_WpResponse";
  }

  static const char* value(const ::waypoints::Load_WpResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::waypoints::Load_WpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success     \n"
;
  }

  static const char* value(const ::waypoints::Load_WpResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::waypoints::Load_WpResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Load_WpResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::waypoints::Load_WpResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::waypoints::Load_WpResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAYPOINTS_MESSAGE_LOAD_WPRESPONSE_H
