// Generated by gencpp from file waypoints/Load_Wp.msg
// DO NOT EDIT!


#ifndef WAYPOINTS_MESSAGE_LOAD_WP_H
#define WAYPOINTS_MESSAGE_LOAD_WP_H

#include <ros/service_traits.h>


#include <waypoints/Load_WpRequest.h>
#include <waypoints/Load_WpResponse.h>


namespace waypoints
{

struct Load_Wp
{

typedef Load_WpRequest Request;
typedef Load_WpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Load_Wp
} // namespace waypoints


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::waypoints::Load_Wp > {
  static const char* value()
  {
    return "3ece68834e0f1a84f61883f885f71f9f";
  }

  static const char* value(const ::waypoints::Load_Wp&) { return value(); }
};

template<>
struct DataType< ::waypoints::Load_Wp > {
  static const char* value()
  {
    return "waypoints/Load_Wp";
  }

  static const char* value(const ::waypoints::Load_Wp&) { return value(); }
};


// service_traits::MD5Sum< ::waypoints::Load_WpRequest> should match
// service_traits::MD5Sum< ::waypoints::Load_Wp >
template<>
struct MD5Sum< ::waypoints::Load_WpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::waypoints::Load_Wp >::value();
  }
  static const char* value(const ::waypoints::Load_WpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoints::Load_WpRequest> should match
// service_traits::DataType< ::waypoints::Load_Wp >
template<>
struct DataType< ::waypoints::Load_WpRequest>
{
  static const char* value()
  {
    return DataType< ::waypoints::Load_Wp >::value();
  }
  static const char* value(const ::waypoints::Load_WpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::waypoints::Load_WpResponse> should match
// service_traits::MD5Sum< ::waypoints::Load_Wp >
template<>
struct MD5Sum< ::waypoints::Load_WpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::waypoints::Load_Wp >::value();
  }
  static const char* value(const ::waypoints::Load_WpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoints::Load_WpResponse> should match
// service_traits::DataType< ::waypoints::Load_Wp >
template<>
struct DataType< ::waypoints::Load_WpResponse>
{
  static const char* value()
  {
    return DataType< ::waypoints::Load_Wp >::value();
  }
  static const char* value(const ::waypoints::Load_WpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAYPOINTS_MESSAGE_LOAD_WP_H
