// Generated by gencpp from file waypoints/waypoint_array.msg
// DO NOT EDIT!


#ifndef WAYPOINTS_MESSAGE_WAYPOINT_ARRAY_H
#define WAYPOINTS_MESSAGE_WAYPOINT_ARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <waypoints/waypoint_msg.h>
#include <waypoints/waypoint_group.h>

namespace waypoints
{
template <class ContainerAllocator>
struct waypoint_array_
{
  typedef waypoint_array_<ContainerAllocator> Type;

  waypoint_array_()
    : header()
    , waypoints()
    , groups()  {
    }
  waypoint_array_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , waypoints(_alloc)
    , groups(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _header_type;
  _header_type header;

   typedef std::vector< ::waypoints::waypoint_msg_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::waypoints::waypoint_msg_<ContainerAllocator> >> _waypoints_type;
  _waypoints_type waypoints;

   typedef std::vector< ::waypoints::waypoint_group_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::waypoints::waypoint_group_<ContainerAllocator> >> _groups_type;
  _groups_type groups;





  typedef boost::shared_ptr< ::waypoints::waypoint_array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::waypoints::waypoint_array_<ContainerAllocator> const> ConstPtr;

}; // struct waypoint_array_

typedef ::waypoints::waypoint_array_<std::allocator<void> > waypoint_array;

typedef boost::shared_ptr< ::waypoints::waypoint_array > waypoint_arrayPtr;
typedef boost::shared_ptr< ::waypoints::waypoint_array const> waypoint_arrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::waypoints::waypoint_array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::waypoints::waypoint_array_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::waypoints::waypoint_array_<ContainerAllocator1> & lhs, const ::waypoints::waypoint_array_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.waypoints == rhs.waypoints &&
    lhs.groups == rhs.groups;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::waypoints::waypoint_array_<ContainerAllocator1> & lhs, const ::waypoints::waypoint_array_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace waypoints

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::waypoints::waypoint_array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoints::waypoint_array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waypoints::waypoint_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waypoints::waypoint_array_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoints::waypoint_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoints::waypoint_array_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::waypoints::waypoint_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "50bb2806cd484cc8094f17a9e088e071";
  }

  static const char* value(const ::waypoints::waypoint_array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x50bb2806cd484cc8ULL;
  static const uint64_t static_value2 = 0x094f17a9e088e071ULL;
};

template<class ContainerAllocator>
struct DataType< ::waypoints::waypoint_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "waypoints/waypoint_array";
  }

  static const char* value(const ::waypoints::waypoint_array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::waypoints::waypoint_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string header\n"
"waypoints/waypoint_msg[] waypoints\n"
"waypoints/waypoint_group[] groups\n"
"\n"
"================================================================================\n"
"MSG: waypoints/waypoint_msg\n"
"string name\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: waypoints/waypoint_group\n"
"string name\n"
"string[] wp_list\n"
;
  }

  static const char* value(const ::waypoints::waypoint_array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::waypoints::waypoint_array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.waypoints);
      stream.next(m.groups);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct waypoint_array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::waypoints::waypoint_array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::waypoints::waypoint_array_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.header);
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::waypoints::waypoint_msg_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
    s << indent << "groups[]" << std::endl;
    for (size_t i = 0; i < v.groups.size(); ++i)
    {
      s << indent << "  groups[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::waypoints::waypoint_group_<ContainerAllocator> >::stream(s, indent + "    ", v.groups[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAYPOINTS_MESSAGE_WAYPOINT_ARRAY_H
