// Generated by gencpp from file waypoints/waypoint_group.msg
// DO NOT EDIT!


#ifndef WAYPOINTS_MESSAGE_WAYPOINT_GROUP_H
#define WAYPOINTS_MESSAGE_WAYPOINT_GROUP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace waypoints
{
template <class ContainerAllocator>
struct waypoint_group_
{
  typedef waypoint_group_<ContainerAllocator> Type;

  waypoint_group_()
    : name()
    , wp_list()  {
    }
  waypoint_group_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , wp_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _wp_list_type;
  _wp_list_type wp_list;





  typedef boost::shared_ptr< ::waypoints::waypoint_group_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::waypoints::waypoint_group_<ContainerAllocator> const> ConstPtr;

}; // struct waypoint_group_

typedef ::waypoints::waypoint_group_<std::allocator<void> > waypoint_group;

typedef boost::shared_ptr< ::waypoints::waypoint_group > waypoint_groupPtr;
typedef boost::shared_ptr< ::waypoints::waypoint_group const> waypoint_groupConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::waypoints::waypoint_group_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::waypoints::waypoint_group_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::waypoints::waypoint_group_<ContainerAllocator1> & lhs, const ::waypoints::waypoint_group_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.wp_list == rhs.wp_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::waypoints::waypoint_group_<ContainerAllocator1> & lhs, const ::waypoints::waypoint_group_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace waypoints

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::waypoints::waypoint_group_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoints::waypoint_group_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waypoints::waypoint_group_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waypoints::waypoint_group_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoints::waypoint_group_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoints::waypoint_group_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::waypoints::waypoint_group_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c03d3488d6139e5ffcdaeff205e40b93";
  }

  static const char* value(const ::waypoints::waypoint_group_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc03d3488d6139e5fULL;
  static const uint64_t static_value2 = 0xfcdaeff205e40b93ULL;
};

template<class ContainerAllocator>
struct DataType< ::waypoints::waypoint_group_<ContainerAllocator> >
{
  static const char* value()
  {
    return "waypoints/waypoint_group";
  }

  static const char* value(const ::waypoints::waypoint_group_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::waypoints::waypoint_group_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string[] wp_list\n"
;
  }

  static const char* value(const ::waypoints::waypoint_group_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::waypoints::waypoint_group_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.wp_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct waypoint_group_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::waypoints::waypoint_group_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::waypoints::waypoint_group_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "wp_list[]" << std::endl;
    for (size_t i = 0; i < v.wp_list.size(); ++i)
    {
      s << indent << "  wp_list[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.wp_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAYPOINTS_MESSAGE_WAYPOINT_GROUP_H
