// Generated by gencpp from file waypoints/Wp_2_Group.msg
// DO NOT EDIT!


#ifndef WAYPOINTS_MESSAGE_WP_2_GROUP_H
#define WAYPOINTS_MESSAGE_WP_2_GROUP_H

#include <ros/service_traits.h>


#include <waypoints/Wp_2_GroupRequest.h>
#include <waypoints/Wp_2_GroupResponse.h>


namespace waypoints
{

struct Wp_2_Group
{

typedef Wp_2_GroupRequest Request;
typedef Wp_2_GroupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Wp_2_Group
} // namespace waypoints


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::waypoints::Wp_2_Group > {
  static const char* value()
  {
    return "09d585458d996891c104c93e1abec1de";
  }

  static const char* value(const ::waypoints::Wp_2_Group&) { return value(); }
};

template<>
struct DataType< ::waypoints::Wp_2_Group > {
  static const char* value()
  {
    return "waypoints/Wp_2_Group";
  }

  static const char* value(const ::waypoints::Wp_2_Group&) { return value(); }
};


// service_traits::MD5Sum< ::waypoints::Wp_2_GroupRequest> should match
// service_traits::MD5Sum< ::waypoints::Wp_2_Group >
template<>
struct MD5Sum< ::waypoints::Wp_2_GroupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::waypoints::Wp_2_Group >::value();
  }
  static const char* value(const ::waypoints::Wp_2_GroupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoints::Wp_2_GroupRequest> should match
// service_traits::DataType< ::waypoints::Wp_2_Group >
template<>
struct DataType< ::waypoints::Wp_2_GroupRequest>
{
  static const char* value()
  {
    return DataType< ::waypoints::Wp_2_Group >::value();
  }
  static const char* value(const ::waypoints::Wp_2_GroupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::waypoints::Wp_2_GroupResponse> should match
// service_traits::MD5Sum< ::waypoints::Wp_2_Group >
template<>
struct MD5Sum< ::waypoints::Wp_2_GroupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::waypoints::Wp_2_Group >::value();
  }
  static const char* value(const ::waypoints::Wp_2_GroupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoints::Wp_2_GroupResponse> should match
// service_traits::DataType< ::waypoints::Wp_2_Group >
template<>
struct DataType< ::waypoints::Wp_2_GroupResponse>
{
  static const char* value()
  {
    return DataType< ::waypoints::Wp_2_Group >::value();
  }
  static const char* value(const ::waypoints::Wp_2_GroupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAYPOINTS_MESSAGE_WP_2_GROUP_H
